export const ADD_COLUMN_TO_DISPLAY_LIST = 'ADD_COLUMN_TO_DISPLAY_LIST';
export const REMOVE_COLUMN_FROM_DISPLAY_LIST = 'REMOVE_COLUMN_FROM_DISPLAY_LIST';
export const GET_COLUMNS_FROM_DISPLAY_LIST = 'GET_COLUMNS_FROM_DISPLAY_LIST';

