// Transaction details Actions

export const TRANSACTIONS_COLUMN_DATA = 'TRANSACTIONS_COLUMN_DATA';
export const TRANSACTIONS_DETAILS_DATA = 'TRANSACTIONS_DETAILS_DATA';
export const ON_TRANSACTION_CHANGE = 'ON_TRANSACTION_CHANGE';

